; IonityEdge · K10 — ON-DEVICE build using DFRobot's official UNIHIKER platform.
; Brings the unihiker_k10 library (screen/sensors/RGB/audio) + correct pins.
; © Ionity (Pty) Ltd · Policy 986 AED · CC BY-SA 4.0

[env:unihiker_k10]
platform = https://github.com/DFRobot/platform-unihiker
board = unihiker_k10
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    bblanchon/ArduinoJson @ ^7.0.4
build_flags =
    -DEDGE_HOST=\"192.168.124.5\"
    -DEDGE_PORT=8765
